fix regression introduced in 25db0a4; fix for displayDriver.h case sensitive filename
BitMaker-hub/NerdMiner_v2 pull request #201
Opened 2023-10-12 13:24 UTC by giovantenne

- fix regression introduced in 25db0a4 that prevented T-Display_V1 display to updates; 
- fix for displayDriver.h case sensitive filename as mentioned here: https://github.com/BitMaker-hub/NerdMiner_v2/issues/200

2023-10-23 20:52 UTC, BitMaker-hub requested changes
Can you do that changes, please?

2023-10-23 20:52 UTC, BitMaker-hub commented on src/drivers/displays/tDisplayV1Driver.cpp
> -  background.deleteSprite();
Hi! Not sure if this should be deleted. 
There is a really lack of memory on this devices so must be added

2023-10-23 20:52 UTC, BitMaker-hub commented on src/drivers/displays/tDisplayV1Driver.cpp
> -  background.deleteSprite();
Hi! Not sure if this should be deleted. 
There is a really lack of memory on this devices so must be added

2023-10-24 08:11 UTC, giovantenne commented
Re-adding deleteSprite() will no solve the memory issues during SSL negotiation when fetching price and stats so I think we should find a different workaround.

2023-10-24 08:19 UTC, BitMaker-hub commented
Allright, let me merge and give it a try this week

2023-10-24 08:20 UTC, merged